<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0-SNAPSHOT
 */

namespace winwin\metric\servant;

use wenbinye\tars\protocol\annotation\TarsProperty;

final class MetricSeries
{
    /**
     * @TarsProperty(order = 0, required = true, type = "Metric")
     *
     * @var \winwin\metric\servant\Metric
     */
    public $metric;

    /**
     * @TarsProperty(order = 1, required = true, type = "vector<map<string, double>>")
     *
     * @var array
     */
    public $values;
}
