<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0-SNAPSHOT
 */

namespace winwin\metric\servant;

use kuiper\helper\Enum;

final class TimeAggregation extends Enum
{
    const NONE = 0;
    const WEEKLY = 1;
    const MONTHLY = 2;
    const YEARLY = 3;
}
